# include:
#   - ../postgres/docker-compose.yaml
#   - ../rabbitmq/docker-compose.yaml
  
services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount the local app directory for live development
      - external-storage:/media/uploads # Mount external storage volume
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERSION_EXCHANGE: "conversion_exchange"
      CONVERSION_KEY: "conversion"
      CONFIRMATION_KEY: "finish-conversion"
      VIDEO_ROOT_PATH: "/media/uploads"
      QUEUE_NAME: "video_conversion_queue"

      CLOUDINARY_CLOUD_NAME: "dl9y4y0iv"
      CLOUDINARY_API_KEY: "549754426677726"
      CLOUDINARY_API_SECRET: "ERi8ZEB70ORrdMy9-y9AW9ArjGI"
    depends_on:
      - postgres
      - rabbitmq


volumes:
  external-storage:
    external: true
